
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 03 19:39:55 ART 2024
//----------------------------------------------------

package Clases;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Jul 03 19:39:55 ART 2024
  */
public class Gramatica extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Gramatica() {super();}

  /** Constructor which sets the default scanner. */
  public Gramatica(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Gramatica(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\044\000\002\002\004\000\002\007\003\000\002\007" +
    "\003\000\002\007\003\000\002\007\003\000\002\007\003" +
    "\000\002\012\003\000\002\012\003\000\002\012\003\000" +
    "\002\002\011\000\002\003\006\000\002\003\005\000\002" +
    "\004\010\000\002\004\007\000\002\004\011\000\002\004" +
    "\004\000\002\004\003\000\002\005\016\000\002\006\006" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\003\000\002" +
    "\006\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\122\000\026\004\021\006\016\007\022\010\012\022" +
    "\013\034\006\035\005\036\015\037\023\042\017\001\002" +
    "\000\004\002\124\001\002\000\004\004\111\001\002\000" +
    "\006\004\021\022\013\001\002\000\032\002\000\004\000" +
    "\007\000\010\000\011\000\016\000\022\000\034\000\036" +
    "\000\037\000\042\000\057\000\001\002\000\032\002\uffff" +
    "\004\uffff\007\uffff\010\uffff\011\uffff\016\uffff\022\uffff\034" +
    "\uffff\036\uffff\037\uffff\042\uffff\057\uffff\001\002\000\032" +
    "\002\ufffd\004\ufffd\007\ufffd\010\ufffd\011\ufffd\016\ufffd\022" +
    "\ufffd\034\ufffd\036\ufffd\037\ufffd\042\ufffd\057\ufffd\001\002" +
    "\000\022\004\021\007\022\010\012\022\013\034\006\036" +
    "\015\037\023\042\017\001\002\000\036\002\uffe9\004\uffe9" +
    "\007\uffe9\010\uffe9\011\uffe9\013\uffe9\016\uffe9\022\uffe9\034" +
    "\uffe9\036\uffe9\037\uffe9\042\uffe9\043\uffe9\057\uffe9\001\002" +
    "\000\034\002\ufffc\004\ufffc\007\ufffc\010\ufffc\011\ufffc\013" +
    "\033\016\ufffc\022\ufffc\034\ufffc\036\ufffc\037\ufffc\042\ufffc" +
    "\057\ufffc\001\002\000\004\053\075\001\002\000\004\004" +
    "\067\001\002\000\032\002\ufff1\004\ufff1\007\ufff1\010\ufff1" +
    "\011\ufff1\016\ufff1\022\ufff1\034\ufff1\036\ufff1\037\ufff1\042" +
    "\ufff1\057\ufff1\001\002\000\032\002\ufffe\004\ufffe\007\ufffe" +
    "\010\ufffe\011\ufffe\016\ufffe\022\ufffe\034\ufffe\036\ufffe\037" +
    "\ufffe\042\ufffe\057\ufffe\001\002\000\060\002\uffe8\004\uffe8" +
    "\007\uffe8\010\uffe8\011\uffe8\012\054\013\uffe8\014\047\015" +
    "\053\016\uffe8\022\uffe8\034\uffe8\036\uffe8\037\uffe8\040\052" +
    "\042\uffe8\043\uffe8\045\056\046\050\047\057\050\055\053" +
    "\046\057\uffe8\001\002\000\010\004\021\007\022\022\013" +
    "\001\002\000\004\053\024\001\002\000\006\004\021\022" +
    "\013\001\002\000\004\057\026\001\002\000\022\004\021" +
    "\007\022\010\012\022\013\034\006\036\015\037\023\042" +
    "\017\001\002\000\032\002\ufffb\004\ufffb\007\ufffb\010\ufffb" +
    "\011\ufffb\016\ufffb\022\ufffb\034\ufffb\036\ufffb\037\ufffb\042" +
    "\ufffb\057\ufffb\001\002\000\032\002\ufffa\004\ufffa\007\ufffa" +
    "\010\ufffa\011\ufffa\016\ufffa\022\ufffa\034\ufffa\036\ufffa\037" +
    "\ufffa\042\ufffa\057\ufffa\001\002\000\034\002\ufff9\004\ufff9" +
    "\007\ufff9\010\ufff9\011\ufff9\013\033\016\ufff9\022\ufff9\034" +
    "\ufff9\036\ufff9\037\ufff9\042\ufff9\057\ufff9\001\002\000\032" +
    "\002\ufff4\004\ufff4\007\ufff4\010\ufff4\011\ufff4\016\ufff4\022" +
    "\ufff4\034\ufff4\036\ufff4\037\ufff4\042\ufff4\057\ufff4\001\002" +
    "\000\014\017\036\020\041\021\035\033\040\041\034\001" +
    "\002\000\032\002\uffe6\004\uffe6\007\uffe6\010\uffe6\011\uffe6" +
    "\016\uffe6\022\uffe6\034\uffe6\036\uffe6\037\uffe6\042\uffe6\057" +
    "\uffe6\001\002\000\032\002\uffe3\004\uffe3\007\uffe3\010\uffe3" +
    "\011\uffe3\016\uffe3\022\uffe3\034\uffe3\036\uffe3\037\uffe3\042" +
    "\uffe3\057\uffe3\001\002\000\032\002\uffe5\004\uffe5\007\uffe5" +
    "\010\uffe5\011\uffe5\016\uffe5\022\uffe5\034\uffe5\036\uffe5\037" +
    "\uffe5\042\uffe5\057\uffe5\001\002\000\032\002\ufff6\004\ufff6" +
    "\007\ufff6\010\ufff6\011\ufff6\016\ufff6\022\ufff6\034\ufff6\036" +
    "\ufff6\037\ufff6\042\ufff6\057\ufff6\001\002\000\032\002\uffe7" +
    "\004\uffe7\007\uffe7\010\uffe7\011\uffe7\016\uffe7\022\uffe7\034" +
    "\uffe7\036\uffe7\037\uffe7\042\uffe7\057\uffe7\001\002\000\032" +
    "\002\uffe4\004\uffe4\007\uffe4\010\uffe4\011\uffe4\016\uffe4\022" +
    "\uffe4\034\uffe4\036\uffe4\037\uffe4\042\uffe4\057\uffe4\001\002" +
    "\000\004\011\044\001\002\000\004\013\033\001\002\000" +
    "\026\004\021\006\016\007\022\010\012\022\013\034\006" +
    "\035\005\036\015\037\023\042\017\001\002\000\032\002" +
    "\ufff7\004\ufff7\007\ufff7\010\ufff7\011\ufff7\016\ufff7\022\ufff7" +
    "\034\ufff7\036\ufff7\037\ufff7\042\ufff7\057\ufff7\001\002\000" +
    "\006\004\021\022\013\001\002\000\006\004\021\022\013" +
    "\001\002\000\004\004\uffe1\001\002\000\004\004\063\001" +
    "\002\000\004\004\uffde\001\002\000\006\004\062\005\061" +
    "\001\002\000\006\004\021\022\013\001\002\000\004\004" +
    "\uffdf\001\002\000\004\004\uffe2\001\002\000\004\004\uffe0" +
    "\001\002\000\036\002\uffeb\004\uffeb\007\uffeb\010\uffeb\011" +
    "\uffeb\013\uffeb\016\uffeb\022\uffeb\034\uffeb\036\uffeb\037\uffeb" +
    "\042\uffeb\043\uffeb\057\uffeb\001\002\000\036\002\uffec\004" +
    "\uffec\007\uffec\010\uffec\011\uffec\013\uffec\016\uffec\022\uffec" +
    "\034\uffec\036\uffec\037\uffec\042\uffec\043\uffec\057\uffec\001" +
    "\002\000\036\002\uffed\004\uffed\007\uffed\010\uffed\011\uffed" +
    "\013\uffed\016\uffed\022\uffed\034\uffed\036\uffed\037\uffed\042" +
    "\uffed\043\uffed\057\uffed\001\002\000\036\002\uffea\004\uffea" +
    "\007\uffea\010\uffea\011\uffea\013\uffea\016\uffea\022\uffea\034" +
    "\uffea\036\uffea\037\uffea\042\uffea\043\uffea\057\uffea\001\002" +
    "\000\036\002\uffee\004\uffee\007\uffee\010\uffee\011\uffee\013" +
    "\uffee\016\uffee\022\uffee\034\uffee\036\uffee\037\uffee\042\uffee" +
    "\043\uffee\057\uffee\001\002\000\004\057\066\001\002\000" +
    "\036\002\uffef\004\uffef\007\uffef\010\uffef\011\uffef\013\uffef" +
    "\016\uffef\022\uffef\034\uffef\036\uffef\037\uffef\042\uffef\043" +
    "\uffef\057\uffef\001\002\000\004\053\070\001\002\000\006" +
    "\004\021\022\013\001\002\000\004\057\072\001\002\000" +
    "\004\011\073\001\002\000\026\004\021\006\016\007\022" +
    "\010\012\022\013\034\006\035\005\036\015\037\023\042" +
    "\017\001\002\000\032\002\ufff8\004\ufff8\007\ufff8\010\ufff8" +
    "\011\ufff8\016\ufff8\022\ufff8\034\ufff8\036\ufff8\037\ufff8\042" +
    "\ufff8\057\ufff8\001\002\000\006\004\021\022\013\001\002" +
    "\000\004\057\077\001\002\000\004\011\100\001\002\000" +
    "\022\004\021\007\022\010\012\022\013\034\006\036\015" +
    "\037\023\042\017\001\002\000\032\002\ufff5\004\ufff5\007" +
    "\ufff5\010\ufff5\011\ufff5\016\ufff5\022\ufff5\034\ufff5\036\ufff5" +
    "\037\ufff5\042\ufff5\057\ufff5\001\002\000\032\002\ufff2\004" +
    "\ufff2\007\ufff2\010\ufff2\011\ufff2\016\ufff2\022\ufff2\034\ufff2" +
    "\036\ufff2\037\ufff2\042\ufff2\057\ufff2\001\002\000\004\043" +
    "\104\001\002\000\022\004\021\007\022\010\012\022\013" +
    "\034\006\036\015\037\023\042\017\001\002\000\004\016" +
    "\106\001\002\000\022\004\021\007\022\010\012\022\013" +
    "\034\006\036\015\037\023\042\017\001\002\000\022\004" +
    "\021\007\022\010\012\022\013\034\006\036\015\037\023" +
    "\042\017\001\002\000\032\002\ufff3\004\ufff3\007\ufff3\010" +
    "\ufff3\011\ufff3\016\ufff3\022\ufff3\034\ufff3\036\ufff3\037\ufff3" +
    "\042\ufff3\057\ufff3\001\002\000\004\053\112\001\002\000" +
    "\010\004\021\007\022\022\013\001\002\000\004\057\114" +
    "\001\002\000\004\013\115\001\002\000\014\017\036\020" +
    "\041\021\035\033\040\041\034\001\002\000\004\011\117" +
    "\001\002\000\004\010\120\001\002\000\022\004\021\007" +
    "\022\010\012\022\013\034\006\036\015\037\023\042\017" +
    "\001\002\000\004\011\122\001\002\000\026\004\021\006" +
    "\016\007\022\010\012\022\013\034\006\035\005\036\015" +
    "\037\023\042\017\001\002\000\032\002\ufff0\004\ufff0\007" +
    "\ufff0\010\ufff0\011\ufff0\016\ufff0\022\ufff0\034\ufff0\036\ufff0" +
    "\037\ufff0\042\ufff0\057\ufff0\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\122\000\016\002\006\003\007\004\010\005\017\006" +
    "\013\007\003\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\102\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\003\026\004\027\006\030" +
    "\012\101\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\050\001\001\000\006\003\041\006" +
    "\042\001\001\000\002\001\001\000\004\006\024\001\001" +
    "\000\002\001\001\000\012\003\026\004\027\006\030\012" +
    "\031\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\036\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\002\006\003\007\004\010" +
    "\005\017\006\013\007\044\001\001\000\002\001\001\000" +
    "\004\006\064\001\001\000\004\006\063\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\057\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\070\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\002\006\003\007\004\010\005\017\006\013\007" +
    "\073\001\001\000\002\001\001\000\004\006\075\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\003\026\004" +
    "\027\006\030\012\100\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\003\026\004\027\006" +
    "\030\012\104\001\001\000\002\001\001\000\012\003\026" +
    "\004\027\006\030\012\106\001\001\000\012\003\026\004" +
    "\027\006\030\012\107\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\112\006\042\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\115\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\003\026\004\027\006" +
    "\030\012\120\001\001\000\002\001\001\000\016\002\006" +
    "\003\007\004\010\005\017\006\013\007\122\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Gramatica$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Gramatica$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Gramatica$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol sintaxis;
    
    public void syntax_error(Symbol s){
        this.sintaxis = s;
    }

    public Symbol getS(){
        return this.sintaxis;
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Gramatica$actions {
  private final Gramatica parser;

  /** Constructor */
  CUP$Gramatica$actions(Gramatica parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Gramatica$do_action(
    int                        CUP$Gramatica$act_num,
    java_cup.runtime.lr_parser CUP$Gramatica$parser,
    java.util.Stack            CUP$Gramatica$stack,
    int                        CUP$Gramatica$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Gramatica$result;

      /* select the action based on the action number */
      switch (CUP$Gramatica$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // OPERACION ::= RESERVADO_SUMA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("OPERACION",7, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // OPERACION ::= RESERVADO_RESTA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("OPERACION",7, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // OPERACION ::= RESERVADO_MODULO 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("OPERACION",7, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // OPERACION ::= RESERVADO_DIVISION 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("OPERACION",7, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // OPERACION ::= RESERVADO_MULTIPLICACION 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("OPERACION",7, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // TIPO_DATO ::= RESERVADO_CHAR 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",6, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // TIPO_DATO ::= RESERVADO_FLOAT 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",6, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // TIPO_DATO ::= RESERVADO_STRING 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",6, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // TIPO_DATO ::= RESERVADO_ENTERO 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",6, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // TIPO_DATO ::= RESERVADO_BOOLEAN 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("TIPO_DATO",6, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Instruccion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Instruccion ::= SIMBOLO_SALTO_DE_LINEA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Instruccion ::= IDENTIFICADOR OPERACION IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-2)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Instruccion ::= IDENTIFICADOR SIMBOLO_COMA Instruccion 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-2)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Instruccion ::= IDENTIFICADOR SIMBOLO_IGUALDAD NUMERO 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-2)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Instruccion ::= IDENTIFICADOR SIMBOLO_IGUALDAD IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-2)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Instruccion ::= IDENTIFICADOR SIMBOLO_ASIGNACION Instruccion 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-2)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Instruccion ::= IDENTIFICADOR SIMBOLO_PARENTESIS_ABIERTO Instruccion SIMBOLO_PARENTESIS_CERRADO 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("Instruccion",4, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-3)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // FUNCION ::= RESERVADO_FUNCION IDENTIFICADOR SIMBOLO_PARENTESIS_ABIERTO VARIABLES SIMBOLO_PARENTESIS_CERRADO SIMBOLO_DOS_PUNTOS TIPO_DATO SIMBOLO_PUNTO_Y_COMA RESERVADO_INICIO BLOQUES SIMBOLO_PUNTO_Y_COMA PROGRAMA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("FUNCION",3, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-11)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SENTENCIA ::= RESERVADO_FIN 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTENCIA ::= RESERVADO_INICIO BLOQUES 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-1)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= RESERVADO_SI Instruccion RESERVADO_ENTONCES BLOQUES RESERVADO_SINO BLOQUES BLOQUES 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-6)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= RESERVADO_ESCRIBIR SIMBOLO_PARENTESIS_ABIERTO Instruccion SIMBOLO_PARENTESIS_CERRADO BLOQUES 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-4)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= RESERVADO_LEER SIMBOLO_PARENTESIS_ABIERTO Instruccion SIMBOLO_PARENTESIS_CERRADO SIMBOLO_PUNTO_Y_COMA BLOQUES 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("SENTENCIA",2, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-5)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // VARIABLES ::= Instruccion SIMBOLO_DOS_PUNTOS TIPO_DATO 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("VARIABLES",1, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-2)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // VARIABLES ::= RESERVADO_VARIABLES VARIABLES SIMBOLO_PUNTO_Y_COMA PROGRAMA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("VARIABLES",1, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-3)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // INICIO ::= RESERVADO_PROGRAMA IDENTIFICADOR SIMBOLO_PARENTESIS_ABIERTO Instruccion SIMBOLO_PARENTESIS_CERRADO SIMBOLO_PUNTO_Y_COMA PROGRAMA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-6)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // BLOQUES ::= Instruccion 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("BLOQUES",8, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // BLOQUES ::= SENTENCIA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("BLOQUES",8, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // BLOQUES ::= VARIABLES 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("BLOQUES",8, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // PROGRAMA ::= Instruccion 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("PROGRAMA",5, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // PROGRAMA ::= SENTENCIA 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("PROGRAMA",5, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // PROGRAMA ::= FUNCION 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("PROGRAMA",5, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROGRAMA ::= VARIABLES 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("PROGRAMA",5, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // PROGRAMA ::= INICIO 
            {
              Object RESULT =null;

              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("PROGRAMA",5, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          return CUP$Gramatica$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= PROGRAMA EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-1)).value;
		RESULT = start_val;
              CUP$Gramatica$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Gramatica$stack.elementAt(CUP$Gramatica$top-1)), ((java_cup.runtime.Symbol)CUP$Gramatica$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Gramatica$parser.done_parsing();
          return CUP$Gramatica$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

