/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.Lexer;
import javax.swing.JFileChooser;
import static Clases.Tokens.*;
import static Clases.Gramatica.*;
import java.awt.Color;
import java_cup.runtime.Symbol;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class PantallaPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form PantallaPrincipal
	 */
	public PantallaPrincipal() {
		initComponents();
		setTitle("Analizar léxico y sintáctico");
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRS = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRL = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnCA = new javax.swing.JButton();
        btnVE = new javax.swing.JButton();
        btnVR = new javax.swing.JButton();
        btnAL = new javax.swing.JButton();
        btnAS = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnLC = new javax.swing.JButton();
        lblArchivo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtED = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Análisis Sintáctico"));

        txtRS.setEditable(false);
        txtRS.setColumns(20);
        txtRS.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtRS.setRows(5);
        jScrollPane3.setViewportView(txtRS);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Análisi Léxico"));

        txtRL.setEditable(false);
        txtRL.setColumns(20);
        txtRL.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtRL.setRows(5);
        jScrollPane2.setViewportView(txtRL);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setDoubleBuffered(false);

        btnCA.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnCA.setText("Abrir un Archivo");
        btnCA.setToolTipText("");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });

        btnVE.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnVE.setText("Vaciar Entrada");
        btnVE.setToolTipText("");
        btnVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVEActionPerformed(evt);
            }
        });

        btnVR.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnVR.setText("Vaciar Resultados");
        btnVR.setToolTipText("");
        btnVR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVRActionPerformed(evt);
            }
        });

        btnAL.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnAL.setText("Analizar Léxico");
        btnAL.setToolTipText("");
        btnAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALActionPerformed(evt);
            }
        });

        btnAS.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnAS.setText("Analizar Sintáxis");
        btnAS.setToolTipText("");
        btnAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnASActionPerformed(evt);
            }
        });

        btnAC.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnAC.setText("Análisis Completo");
        btnAC.setToolTipText("");
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnLC.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnLC.setText("Limpieza Completa");
        btnLC.setToolTipText("");
        btnLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLCActionPerformed(evt);
            }
        });

        lblArchivo.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAL, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAS, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVE, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVR, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblArchivo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnCA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnCA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAC))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(lblArchivo)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada de Datos"));

        txtED.setColumns(20);
        txtED.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        txtED.setRows(5);
        jScrollPane1.setViewportView(txtED);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Instrucciones de uso: Seleccione un archivo de texto con formato .txt o escriba su código en la entrada de texto, a continuación seleccione el tipo de análisis.");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2))
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
	//boton cargar archivo permite cargar un archivo desde el computador
    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
        // Crear un JFileChooser
		JFileChooser archivoAbierto = new JFileChooser();

		// Mostrar el diálogo de selección de archivo
		int returnVal = archivoAbierto.showOpenDialog(this);

		// Si se selecciona un archivo
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = archivoAbierto.getSelectedFile();

			// Leer el contenido del archivo y mostrarlo en textFieldEntrada
			try (BufferedReader br = new BufferedReader(new FileReader(file))) {
				StringBuilder sb = new StringBuilder();
				String line;
				while ((line = br.readLine()) != null) {
					sb.append(line).append("\n");
				}
				txtED.setText(sb.toString());
				lblArchivo.setText("Archivo Seleccionado: " + file.getName());
			} catch (IOException ex) {
				
			}
		}
    }//GEN-LAST:event_btnCAActionPerformed
	
	//boton vaciar entrada vacia el campo de entrada de datos (txtED)
    private void btnVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVEActionPerformed
        txtED.setText("");
		lblArchivo.setText("");
    }//GEN-LAST:event_btnVEActionPerformed
	//boton vaciar resultados vacia solo los campos de textos de los resultados (txtRL y txtRS)
    private void btnVRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVRActionPerformed
        txtRL.setText("");
		txtRS.setText("");
    }//GEN-LAST:event_btnVRActionPerformed
	//boton analizar analizar lexico analiza solo el lexico
    private void btnALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALActionPerformed
		int cont = 1;
        
        String contenido = (String) txtED.getText();
        ReglasLexicas lexico = new ReglasLexicas(new StringReader(contenido));
        String resultado = "LINEA " + cont + "\t\t\tSIMBOLO\n";
        while (true) {
			try {
				Tokens token = lexico.yylex();
				if (token == null) {
					txtRL.setText(resultado);
					return;
				}
				switch (token) {
					case SIMBOLO_ASIGNACION_MULTIPLICACION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_DIVISION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_PARENTESIS_ABIERTO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_PARENTESIS_CERRADO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_MODULO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_CORCHETE_ABIERTO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_CORCHETE_CERRADO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_RESTA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_SUMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_SALTO_DE_LINEA:
						cont++;
						resultado += "LINEA " + cont + "\n";
						break;
					case SIMBOLO_MULTIPLICACION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_LLAVE_ABIERTA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_LLAVE_CERRADA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_PUNTO_Y_COMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case CARACTER_DESCONOCIDO:
						resultado += "  -> CARACTER DESCONOCIDO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_VARIABLES:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_PROGRAMA:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_ESCRIBIR:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_ENTONCES:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_DOS_PUNTOS:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_FUNCION:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_ENTERO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_INICIO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_MODULO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_IGUALDAD:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_DIVISION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_SINO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_LEER:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_MODULO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_FIN:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_RESTA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case IDENTIFICADOR:
						resultado += "  -> IDENTIFICADOR <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_SI:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_SUMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_COMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case NUMERO:
						resultado += "  -> NÚMERO <-\t\t"+ lexico.lexeme + "\n";
						break;
					default:
						resultado += "  -> " + lexico.lexeme + " <-\n";
						break;
				}
			} catch (IOException ex) {
				JOptionPane.showMessageDialog(this, "Por favor, inserte texto antes de analizar.", "Error", JOptionPane.ERROR_MESSAGE);
			}
        }
    }//GEN-LAST:event_btnALActionPerformed
	//boton Analizar sintaxis analiza solo la sintaxis
    private void btnASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnASActionPerformed
        String contenido = (String) txtED.getText();
		Gramatica sintaxis = new Gramatica(new Clases.ReglasSintacticas(new StringReader(contenido)));
		try {
			sintaxis.parse();
			txtRS.setText("");
			txtRS.setForeground(new Color(25,111,61));
			txtRS.setText("El análisis léxico se completó correctamente \n\n\tNo se han detectado errores");
		} catch (Exception ex) {
			txtRS.setText("");
			Symbol simboloError = sintaxis.getS();
			txtRS.setForeground(Color.red);
			txtRS.setText("Error de sintaxis: \n\tLinea: " + (simboloError.right + 1) + ".\n\tColumna: " + (simboloError.left + 1) + ".\n\tContenido: " + (simboloError.value));
		}
    }//GEN-LAST:event_btnASActionPerformed
	//boton analisis completo, analiza el léxico y la sintaxis
    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
       
		String contenido1 = (String) txtED.getText();
		Gramatica sintaxis = new Gramatica(new Clases.ReglasSintacticas(new StringReader(contenido1)));
		try {
			sintaxis.parse();
			txtRS.setText("");
			txtRS.setForeground(new Color(25,111,61));
			txtRS.setText("El análisis léxico se completó correctamente \n\n\tNo se han detectado errores");
		} catch (Exception ex) {
			txtRS.setText("");
			Symbol simboloError = sintaxis.getS();
			txtRS.setForeground(Color.red);
			txtRS.setText("Error de sintaxis: \n\tLinea: " + (simboloError.right + 1) + ".\n\tColumna: " + (simboloError.left + 1) + ".\n\tContenido: " + (simboloError.value));
		}
		
		int cont = 1;
        
        String contenido = (String) txtED.getText();
        ReglasLexicas lexico = new ReglasLexicas(new StringReader(contenido));
        String resultado = "LINEA " + cont + "\t\t\tSIMBOLO\n";
        while (true) {
			try {
				Tokens token = lexico.yylex();
				if (token == null) {
					txtRL.setText(resultado);
					return;
				}
				switch (token) {
					case SIMBOLO_ASIGNACION_MULTIPLICACION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_DIVISION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_PARENTESIS_ABIERTO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_PARENTESIS_CERRADO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_MODULO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_CORCHETE_ABIERTO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_CORCHETE_CERRADO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_RESTA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION_SUMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_SALTO_DE_LINEA:
						cont++;
						resultado += "LINEA " + cont + "\n";
						break;
					case SIMBOLO_MULTIPLICACION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_LLAVE_ABIERTA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_LLAVE_CERRADA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_PUNTO_Y_COMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case CARACTER_DESCONOCIDO:
						resultado += "  -> CARACTER DESCONOCIDO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_VARIABLES:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_PROGRAMA:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_ESCRIBIR:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_ENTONCES:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_DOS_PUNTOS:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_ASIGNACION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_FUNCION:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_ENTERO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_INICIO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_MODULO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_IGUALDAD:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_DIVISION:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_SINO:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_LEER:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_MODULO:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_FIN:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_RESTA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case IDENTIFICADOR:
						resultado += "  -> IDENTIFICADOR <-\t\t" + lexico.lexeme + "\n";
						break;
					case RESERVADO_SI:
						resultado += "  -> RESERVADO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_SUMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case SIMBOLO_COMA:
						resultado += "  -> SÍMBOLO <-\t\t" + lexico.lexeme + "\n";
						break;
					case NUMERO:
						resultado += "  -> NÚMERO <-\t\t"+ lexico.lexeme + "\n";
						break;
					default:
						resultado += "  -> " + lexico.lexeme + " <-\n";
						break;
				}
			} catch (IOException ex) {
				JOptionPane.showMessageDialog(this, "Por favor, inserte texto antes de analizar.", "Error", JOptionPane.ERROR_MESSAGE);
			}
        }
		
    }//GEN-LAST:event_btnACActionPerformed
	//boton Limpieza Completa (Vaciar todos los campos de textos, entrada y resultados)
    private void btnLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLCActionPerformed
        txtRL.setText("");
		txtRS.setText("");
		txtED.setText("");
		lblArchivo.setText("");
    }//GEN-LAST:event_btnLCActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PantallaPrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAL;
    private javax.swing.JButton btnAS;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnLC;
    private javax.swing.JButton btnVE;
    private javax.swing.JButton btnVR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JTextArea txtED;
    private javax.swing.JTextArea txtRL;
    private javax.swing.JTextArea txtRS;
    // End of variables declaration//GEN-END:variables
}
