
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 03 19:39:55 ART 2024
//----------------------------------------------------

package Clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 3;
  public static final int SIMBOLO_PARENTESIS_CERRADO = 45;
  public static final int RESERVADO_SINO = 12;
  public static final int RESERVADO_PROGRAMA = 4;
  public static final int SIMBOLO_LLAVE_ABIERTA = 19;
  public static final int RESERVADO_SI = 26;
  public static final int RESERVADO_MODULO = 37;
  public static final int RESERVADO_SUMA = 30;
  public static final int RESERVADO_ENTONCES = 33;
  public static final int SIMBOLO_ASIGNACION_MODULO = 17;
  public static final int RESERVADO_MULTIPLICACION = 35;
  public static final int SIMBOLO_SUMA = 34;
  public static final int SIMBOLO_ASIGNACION_DIVISION = 43;
  public static final int SIMBOLO_ASIGNACION_SUMA = 39;
  public static final int RESERVADO_VARIABLES = 5;
  public static final int IDENTIFICADOR = 2;
  public static final int RESERVADO_ESCRIBIR = 29;
  public static final int SIMBOLO_PUNTO_Y_COMA = 7;
  public static final int SIMBOLO_DOS_PUNTOS = 9;
  public static final int SIMBOLO_DIVISION = 42;
  public static final int SIMBOLO_COMA = 8;
  public static final int RESERVADO_STRING = 13;
  public static final int SIMBOLO_PARENTESIS_ABIERTO = 41;
  public static final int RESERVADO_INICIO = 6;
  public static final int CARACTER_DESCONOCIDO = 21;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RESERVADO_LEER = 28;
  public static final int RESERVADO_FLOAT = 14;
  public static final int SIMBOLO_CORCHETE_CERRADO = 23;
  public static final int SIMBOLO_MULTIPLICACION = 40;
  public static final int RESERVADO_FUNCION = 27;
  public static final int SIMBOLO_SALTO_DE_LINEA = 16;
  public static final int SIMBOLO_ASIGNACION_RESTA = 44;
  public static final int SIMBOLO_LLAVE_CERRADA = 18;
  public static final int RESERVADO_ENTERO = 31;
  public static final int RESERVADO_FIN = 32;
  public static final int SIMBOLO_MODULO = 20;
  public static final int RESERVADO_CHAR = 15;
  public static final int SIMBOLO_RESTA = 22;
  public static final int SIMBOLO_IGUALDAD = 11;
  public static final int SIMBOLO_ASIGNACION = 10;
  public static final int SIMBOLO_ASIGNACION_MULTIPLICACION = 46;
  public static final int RESERVADO_DIVISION = 36;
  public static final int RESERVADO_RESTA = 38;
  public static final int RESERVADO_BOOLEAN = 25;
  public static final int SIMBOLO_CORCHETE_ABIERTO = 24;
}

