
package Clases;

/**
 *
 * @author Lucas
 */
public enum Tokens {
	SIMBOLO_ASIGNACION_MULTIPLICACION,
	SIMBOLO_ASIGNACION_DIVISION,
	SIMBOLO_PARENTESIS_ABIERTO,
	SIMBOLO_PARENTESIS_CERRADO,
	SIMBOLO_ASIGNACION_MODULO,
	SIMBOLO_CORCHETE_ABIERTO,
	SIMBOLO_CORCHETE_CERRADO,
	SIMBOLO_ASIGNACION_RESTA,
	SIMBOLO_ASIGNACION_SUMA,
	SIMBOLO_SALTO_DE_LINEA,
	SIMBOLO_MULTIPLICACION,
	SIMBOLO_LLAVE_ABIERTA,
	SIMBOLO_LLAVE_CERRADA,
	SIMBOLO_PUNTO_Y_COMA,
	CARACTER_DESCONOCIDO,
	RESERVADO_VARIABLES,
	RESERVADO_PROGRAMA,
	RESERVADO_ESCRIBIR,
	RESERVADO_ENTONCES,
	SIMBOLO_DOS_PUNTOS,
	SIMBOLO_ASIGNACION,
	RESERVADO_FUNCION,
	RESERVADO_BOOLEAN,
	RESERVADO_ENTERO,
	RESERVADO_INICIO,
	RESERVADO_MODULO,
	SIMBOLO_IGUALDAD,
	SIMBOLO_DIVISION,
	RESERVADO_STRING,
	RESERVADO_FLOAT,
	RESERVADO_SINO,
	RESERVADO_LEER,
	SIMBOLO_MODULO,
	RESERVADO_CHAR,
	RESERVADO_FIN,
	SIMBOLO_RESTA,
	IDENTIFICADOR,
	RESERVADO_SI,
	SIMBOLO_SUMA,
	SIMBOLO_COMA,
	NUMERO;
}
